# Generated by Django 6.1 on 2026-08-29 16:51

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Stable identifier e.g. platform.organization:read', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Code must be <namespace>.<resource>:<action> lowercase, e.g. platform.organization:read', regex='^[a-z0-9_]+\\.[a-z0-9_]+:[a-z0-9_]+$')])),
                ('name', models.CharField(help_text='Human-readable name', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'authorization_permission',
                'ordering': ['code'],
            },
        ),
    ]
