# Generated by Django 6.1 on 2026-08-29 16:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rls_user'),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_roles', to='accounts.organizationmembership')),
            ],
            options={
                'verbose_name': 'Membership Role',
                'verbose_name_plural': 'Membership Roles',
                'db_table': 'authorization_membershiprole',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, help_text='Stable key e.g. organization_admin', max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Key must be lowercase alphanumeric with underscores, e.g. organization_admin', regex='^[a-z][a-z0-9_]*$')])),
                ('name', models.CharField(help_text='Human-readable name', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memberships', models.ManyToManyField(blank=True, related_name='roles', through='authorization.MembershipRole', to='accounts.organizationmembership')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions granted by this role', related_name='roles', to='authorization.permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'authorization_role',
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='membershiprole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_roles', to='authorization.role'),
        ),
        migrations.AddConstraint(
            model_name='membershiprole',
            constraint=models.UniqueConstraint(fields=('membership', 'role'), name='unique_membership_role'),
        ),
    ]
