# Generated by Django 6.1 on 2026-08-30 06:08

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


RLS_ENABLE = """
ALTER TABLE authorization_scopedresource ENABLE ROW LEVEL SECURITY;
ALTER TABLE authorization_scopedresource FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON authorization_scopedresource;
CREATE POLICY tenant_isolation ON authorization_scopedresource
    USING (organization_id = nullif(current_setting('app.current_organization_id', true), '')::uuid)
    WITH CHECK (organization_id = nullif(current_setting('app.current_organization_id', true), '')::uuid);
"""

RLS_DISABLE = """
DROP POLICY IF EXISTS tenant_isolation ON authorization_scopedresource;
ALTER TABLE authorization_scopedresource NO FORCE ROW LEVEL SECURITY;
ALTER TABLE authorization_scopedresource DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rls_user'),
        ('authorization', '0002_membershiprole_role_membershiprole_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopedResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Scoped Resource',
                'verbose_name_plural': 'Scoped Resources',
                'db_table': 'authorization_scopedresource',
                'ordering': ['name'],
            },
            managers=[
            ],
        ),
        migrations.RemoveConstraint(
            model_name='membershiprole',
            name='unique_membership_role',
        ),
        migrations.AddField(
            model_name='membershiprole',
            name='scope_type',
            field=models.CharField(blank=True, default='', help_text="Dimension e.g. '', 'organization', 'region', 'resource'", max_length=64, validators=[django.core.validators.RegexValidator(message='scope_type must be lowercase alphanumeric with underscores', regex='^[a-z][a-z0-9_]*$')]),
        ),
        migrations.AddField(
            model_name='membershiprole',
            name='scope_value',
            field=models.CharField(blank=True, default='', help_text='Value for dimension, e.g. north or resource UUID', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='membershiprole',
            constraint=models.UniqueConstraint(fields=('membership', 'role', 'scope_type', 'scope_value'), name='unique_membership_role_scope'),
        ),
        migrations.AddField(
            model_name='scopedresource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoped_resources', to='accounts.organization'),
        ),
        migrations.RunSQL(RLS_ENABLE, RLS_DISABLE),
    ]
